http_listen_port: 9095
https_enabled: false
repository: ../../tests/tmp/repositories/cucumber
logfile: ../../logs/cucumber-server.log
corsenabled: false
corsorigin: null
database: ../../db/cucumber.db
static: ../../dist
hugo_config_file: ../../config/hugo.development.yml
hugo_bin: /usr/local/bin/hugo
private_key_path: ../../tests/backend/keys/passwords/app.test.rsa
public_key_path: ../../tests/backend/keys/passwords/app.test.rsa.pub
file_categories:
  documents:
    - .md
  images:
    - .png
    - .jpg
    - .gif
  structured data:
    - .xml
    - .json
  tabular data:
    - .csv
media_types:

    # image types
    gif: image/gif
    jpeg: image/jpeg
    jpg: image/jpeg
    png: image/png
    tiff: image/tiff

    # structured data types
    xml: text/xml
    csv: text/csv
    json: text/json
