host: docs.somecompany.com
http_listen_port: 9095
https_enabled: false
repository: ../../tests/tmp/repositories/cucumber
logfile: ../../logs/cucumber-server-ssh.log
database: ../../db/cucumber.db
static: ../../dist
ssh_listen_port: 2323
hugo_config_file: ../../config/hugo.development.yml

# note that this is the same as the repo, we're just testing that
# it clones and not inspecting the content
hugo_theme_path: ../../tests/tmp/repositories/cucumber


hugo_bin: /usr/local/bin/hugo
private_key_path: ../../tests/data/keys/passwords/app.test.rsa
public_key_path: ../../tests/data/keys/passwords/app.test.rsa.pub
ssh_enabled: true
ssh_listen_port: 2223
git_bin_path: /usr/local/bin/
git_user: git
file_categories:
  documents:
    - .md
  images:
    - .png
    - .jpg
    - .gif
  structured data:
    - .xml
    - .json
  tabular data:
    - .csv
media_types:

    # image types
    gif: image/gif
    jpeg: image/jpeg
    jpg: image/jpeg
    png: image/png
    tiff: image/tiff

    # structured data types
    xml: text/xml
    csv: text/csv
    json: text/json
