host: localhost

# HTTP settings
http_listen_port: 8080

# HTTPS settings
https_enabled: false
https_listen_port: 4443
https_key: keys/ssl/server.key
https_cert: keys/ssl/server.cert

repository: hugo/content
logfile: logs/development.log
database: db/development.db
static: ./frontend/public
hugo_config_file: config/hugo.development.yml
hugo_bin: /usr/local/bin/hugo
private_key_path: keys/passwords/app.rsa
public_key_path: keys/passwords/app.rsa.pub
ssh_enabled: true
ssh_listen_port: 2222
git_bin_path: /usr/local/bin/
git_repo_path: ./hugo
git_user: git
file_categories:
  documents:
    - .md
  images:
    - .png
    - .jpg
    - .jpeg
    - .gif
  structured data:
    - .xml
    - .json
  tabular data:
    - .csv
media_types:

    # image types
    bmp: image/bmp
    gif: image/gif
    jpe: image/jpeg
    jpeg: image/jpeg
    jpg: image/jpeg
    png: image/png
    pnz: image/png
    tif: image/tiff
    tiff: image/tiff
    webp: image/webp

    # structured data types
    xml: text/xml
    json: text/json

    # tabular data types
    csv: text/csv

translation_enabled: true

default_language: en
enabled_languages:
  - en
  - es
  - de
  - fr

all_languages:
  en:
    name: English
    flag: 🇬🇧
  es:
    name: Spanish
    flag: 🇪🇸
  fr:
    name: French
    flag: 🇫🇷
  de:
    name: German
    flag: 🇩🇪
  it:
    name: Italian
    flag: 🇮🇹
