port: 8080
repository: repo
logfile: logs/development.log
corsenabled: true
corsorigin: localhost:8080
database: db/development.db
static: ./frontend/public
hugo_config_file: config/hugo.development.yml
hugo_bin: /usr/local/bin/hugo
private_key_path: keys/app.rsa
public_key_path: keys/app.rsa.pub
file_categories:
  documents:
    - .md
  images:
    - .png
    - .jpg
    - .jpeg
    - .gif
  structured data:
    - .xml
    - .json
  tabular data:
    - .csv
media_types:

    # image types
    bmp: image/bmp
    gif: image/gif
    jpe: image/jpeg
    jpeg: image/jpeg
    jpg: image/jpeg
    png: image/png
    pnz: image/png
    tif: image/tiff
    tiff: image/tiff
    webp: image/webp

    # structured data types
    xml: text/xml
    csv: text/csv
