languageCode: "en-gb"
title: "My New Hugo Site"
baseURL: "http://localhost:8080"
buildDrafts: true
theme: ../../graphia-minimal-theme
contentDir: hugo/content
relativeURLs: true
publishDir: frontend/public
preserveTaxonomyNames: true

pygmentsCodeFences: true
pygmentsUseClasses: true

defaultContentLanguage: "en"
defaultContentLanguageInSubdir: false

Languages:
  en:
    name: "English"
    weight: 0
    flag: 🇬🇧

  fr:
    name: "French"
    weight: 1
    flag: 🇫🇷

  de:
    name: "German"
    weight: 1
    flag: 🇩🇪

  es:
    name: "Spanish"
    weight: 1
    flag: 🇪🇸
