port: 8085
repository: repo
logfile: ../logs/test.log
corsenabled: false
corsorigin: null
database: ../tests/tmp/databases/test.db
hugo_config_file: config/hugo.yml
file_categories:
  documents:
    - .md
  images:
    - .png
    - .jpg
    - .gif
  structured data:
    - .xml
    - .json
  tabular data:
    - .csv