host: localhost
http_listen_port: 8085
https_enabled: false
repository: repo
logfile: ../logs/test.log
database: ../tests/tmp/databases/test.db
hugo_config_file: config/hugo.yml
file_categories:
  documents:
    - .md
  images:
    - .png
    - .jpg
    - .gif
  structured data:
    - .xml
    - .json
  tabular data:
    - .csv
media_types:

    # image types
    gif: image/gif
    jpeg: image/jpeg
    jpg: image/jpeg
    png: image/png
    tiff: image/tiff

    # structured data types
    xml: text/xml
    csv: text/csv
    json: text/json

translation_enabled: false
