<template>
	<div v-title="title">

		<Breadcrumbs :levels="breadcrumbs"/>

		<div class="row theme-settings">

			<SettingsNavigation/>

			<article class="col col-md-9">
				<h1>Customising the theme</h1>

				<p>
					If you are familiar with HTML and CSS, you can completely tailor the
					output of Graphia CMS.
				</p>

				<h2>Prerequisites</h2>

				<dl>
					<dt>Git</dt>
					<dd>
						To work with a Git repository, you must have Git installed on your computer.
						Windows users can download it from the <a href="https://gitforwindows.org/">Git for Windows</a>
						and MacOS users can install install via Homebrew

<pre>
<code>
brew install git
</code>
</pre>
					</dd>

					<dt>SSH Key Access</dt>
					<dd>
						If you haven't done so already, before cloning the repository you must
						<router-link :to="{name: 'ssh_key_settings'}">
							add your public SSH key to Graphia CMS
						</router-link>. Once it's saved you should be able to connect
					</dd>

					<dt>Hugo</dt>
					<dd>
						Graphia CMS uses <a href="https://gohugo.io">Hugo</a> as its publishing engine. The customisation process is
						far simpler and quicker when Hugo is installed locally. Any errors or warnings generated by Hugo
						while the theme is being developed will be apparent before any changes are uploaded.
					</dd>

				</dl>


				<div class="alert alert-info">
					<h4 class="alert-heading">Top tip</h4>

					If your SSH listen port is anything other than <code>22</code> or you have multiple SSH keys, you can
					override the default settings when connecting to Graphia CMS by adding an entry like this to your SSH Config.



<pre>
<code>
host graphia
    HostName {{ serverInfo.host }}
    Port {{ serverInfo.ssh_port }}
    IdentityFile ~/.ssh/id_rsa_example_file
</code>
</pre>


				</div>

				<h2>Cloning</h2>

				<p>Now, to clone the content just run the following command</p>

<pre>
<code>
git clone {{ serverInfo.host }}:theme
</code>
</pre>


				<p>If everything worked, you will have a directory called <code>theme</code> in your working directory that
				contains all of the template and style information for sites published by Graphia CMS.</p>

				<p>In the root of the repository you will see a file called <code>README.md</code>, it contains a detailed
				set of customisation instructions and guidelines</p>


			</article>
		</div>

	</div>
</template>

<script>

	import SettingsNavigation from "./Navigation";
	import Breadcrumbs from '../Utilities/Breadcrumbs';
	import PasswordSettings from './MyProfile/PasswordSettings';

	import CMSUser from '../../javascripts/models/user.js';
	import CMSBreadcrumb from '../../javascripts/models/breadcrumb.js';

	export default {
		name: "ThemeSettings",
		data() {
			return {
				 // so we can render the form bound to something
				emptyUser: new CMSUser
			};
		},
		computed: {
			breadcrumbs() {
				return [new CMSBreadcrumb("Theme", "theme_settings")];
			},

			title() {
				return "Settings: Theme";
			},

			serverInfo() {
				return this.$store.state.server.serverInfo;
			},

		},
		methods: {
		},
		components: {
			SettingsNavigation,
			Breadcrumbs,
			PasswordSettings
		}

	};
</script>

<style lang="scss" scoped>
	pre {
		background-color: black;
		color: white;
		margin: 1rem 0.5rem;
		padding: 0rem 2rem;

		> code {
			margin: 0rem;
			padding: 0rem;
		}
	};

	.alert {
		margin: 1rem 0rem;
	}

</style>

